### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rtybanana** [caughtinflux/Apex#2] opened 2016-07-26 13:17 UTC
Springboard crash when attempting to enter edit mode on any nested app

**Comment by caughtinflux** [comment] 2016-07-26 13:55
Duplicate of #1

**Comment by caughtinflux** [comment] 2016-07-26 13:55
Or maybe not? What are the steps to reproduce this crash?

**Comment by rtybanana** [comment] 2016-07-26 14:19
Open any group and tap and hold a nested app, close the group and reopen a different group. Crashes the springboard on the latest hotfix

**Comment by caughtinflux** [comment] 2016-07-26 15:33
@rtybanana please check if the issue still occurs on the latest build

**Comment by rtybanana** [comment] 2016-07-26 15:42
Issue is fixed in the latest build.

rtybanana

**Comment by caughtinflux** [comment] 2016-07-26 16:02
Sweet, thanks!

**Closed as completed by caughtinflux** 2016-07-26 16:02 UTC
